### PR TITLE
Another branch

### PR DESCRIPTION
**Pull request by tjhelsel**
### Assignee Tasks

* [ ] added unit tests (or none needed)
* [ ] written relevant docs (or none needed)
* [ ] referenced any relevant issues (or none exist)

### Guidelines

Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, reasoning behind the current solution, and any other relevant information for posterity.

---

changed name and updated axios version

### CODE REVIEW

**Comment by findkevin** [comment]
@fjiang91 - Please take a look at this request.

**Comment by findkevin** [comment]
@dcnycoder - Please take a look at this request.

**Review by fjiang91 — APPROVED** [review]
Great Job.

**Review by findkevin — APPROVED** [review]
Approved updated README and package.json

**Pull request merged**
